### PR TITLE
[Ready to Publish] Arabic - Introduction to Web Accessibility

### PR DESCRIPTION
**Pull request by ntounsi**
Translation in progress... For initial preview

### CODE REVIEW

**Comment by ntounsi** [comment]
To preview recent changes

**Comment by shawna-slh** [comment]
Hi @ntounsi 

Preview is here: https://deploy-preview-48--wai-intro-accessibility.netlify.com/fundamentals/accessibility-intro/ar

(you shouldn't need to close the pull request for the preview to update -- just wait a few minutes. :-)

Is the preview now showing your changes?

**Comment by ntounsi** [comment]
@slhenry 

> Preview is here: https://deploy-preview-48--wai-intro-accessibility.netlify.com/fundamentals/accessibility-intro/ar

Sorry for that. At some point, it happened that the page was "to long to load".

> Is the preview now showing your changes?

Yes :-) . Need to fix some typos.

**Comment by ntounsi** [comment]
@slhenry,
 
> (you shouldn't need to close the pull request for the preview to update -- just wait a few minutes. :-)
> 
Sorry for that. At some point, it happened that the page was "to long to load".

> Is the preview now showing your changes?

Yes :-). need to fix some typos.

**Comment by shawna-slh** [comment]
I think it was a GitHub-wide issue. Same thing happened to me with a different GitHub repository.

**Comment by ntounsi** [comment]
Finished translation.

**Comment by yatil** [comment]
This is now uploading and should show up in a couple of minutes. Thanks for the translation!

**Comment by ntounsi** [comment]
Reviewing to detect possible typos or bidi nuts.

**Pull request merged**
