### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by shawna-slh**

### CODE REVIEW

**Review by bakkenb — APPROVED** [review]
I am okay with these changes

**Comment by yatil** [comment]
(not a blocker) IMHO If those pages are so important that we want to link them from here, we should unarchive and update them. I don’t think we should draw attention to the fact that they are archived.

**Comment by shawna-slh** [comment]
> IMHO If those pages are so important that we want to link them from here, we should unarchive and update them. I don’t think we should draw attention to the fact that they are archived.

Ideally, I do think that we would have updated listing that provides evidence that aspects of the business case / additional benefits are support by which success criteria. And also updated guidance on figuring out your legal requirements. **However**, it it not a priority above many, many other things that we need to do first.

For now, we're saying these two old pages have specific useful information. Yet we want people to know before they follow the link that the info is not updated and is in a different layout.

It was Sharron's idea to add before the link that it goes to an archived page. I support that.

@yatil - OK?

**Comment by yatil** [comment]
OK.

**Comment by sharronrush** [comment]
I agree with @yatil that "we should unarchive and update them." However, it does not seem like we will get to that anytime soon, so I am ready to live with the less than ideal alternative. (with regret)

**Pull request merged**
