### PR TITLE
[pending reply from VictorBSI] Brazilian Portuguese Translation

### PR DESCRIPTION
**Pull request by VictorBSI**

### CODE REVIEW

**Comment by shawna-slh** [comment]
Hi @VictorBSI I look forward to learning more about your translation. Please see [Translating WAI Resources](https://www.w3.org/WAI/about/translating/). Feel free to contact me directly at shawn@w3.org

**Comment by VictorBSI** [comment]
All Right @slhenry , Thanks for the response, I'll be waiting for your feedback!

**Comment by shawna-slh** [comment]
@VictorBSI ,

I cannot find any background on this translation. Please accept my apologies if I missed e-mail or other communication.

> **Please see [Translating WAI Resources](https://www.w3.org/WAI/about/translating/).**

Do you see the instructions for translations on that page?

If you have any questions,
>  Feel free to contact me directly at shawn@w3.org

Thank you.

**Comment by remibetin** [comment]
Hi @VictorBSI,

I am writing to inform you that I am closing this pull request. Unless we missed e-mail or other communication, we have not received any more background on this translation. And since the original English page has been updated many times since 2019, this translation is unfortunately too outdated.

That being said, if you are still interested in contributing to WAI translations, you are welcome to translate the updated page! The starting point is [Translating WAI Resources](https://www.w3.org/WAI/about/translating/). From there, you will know more about the current process.

After reading this page, the next step would be for you to send an email to @shawna-slh and I at [group-wai-translations@w3.org](mailto:group-wai-translations@w3.org) (not publicly archived) expressing your interest in joining the WAI translator volunteers community.

Thank you.

**Pull request closed without merging**
